# Generated by Django 5.2.1 on 2025-05-24 14:13

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0004_hospitalalbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='doctor_photos/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('qualification', models.CharField(max_length=255)),
                ('specialization', multiselectfield.db.fields.MultiSelectField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('general', 'General Medicine'), ('ent', 'ENT'), ('surgery', 'Surgery'), ('psychiatry', 'Psychiatry')], max_length=86)),
                ('experience_years', models.PositiveIntegerField()),
                ('available_days', multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=56)),
                ('consultation_times', models.TextField(help_text='Comma-separated time slots (e.g., 9:00 AM, 9:30 AM, 10:00 AM)')),
                ('about', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('is_available', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospital.hospital')),
            ],
        ),
    ]
