# Generated by Django 5.2.1 on 2025-05-26 19:03

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='about',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_times',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('allergy_immunology', 'Allergy & Immunology'), ('anesthesiology', 'Anesthesiology'), ('audiology', 'Audiology'), ('cardiology', 'Cardiology'), ('critical_care', 'Critical Care Medicine'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('ent', 'ENT (Ear, Nose & Throat)'), ('family_medicine', 'Family Medicine'), ('gastroenterology', 'Gastroenterology'), ('general_medicine', 'General Medicine'), ('geriatrics', 'Geriatrics'), ('gynecology', 'Gynecology'), ('hematology', 'Hematology'), ('infectious_diseases', 'Infectious Diseases'), ('internal_medicine', 'Internal Medicine'), ('nephrology', 'Nephrology'), ('neurology', 'Neurology'), ('nuclear_medicine', 'Nuclear Medicine'), ('obstetrics', 'Obstetrics'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('pain_management', 'Pain Management'), ('pathology', 'Pathology'), ('pediatrics', 'Pediatrics'), ('plastic_surgery', 'Plastic Surgery'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology'), ('rheumatology', 'Rheumatology'), ('sports_medicine', 'Sports Medicine'), ('surgery', 'Surgery'), ('urology', 'Urology'), ('vascular_surgery', 'Vascular Surgery')], max_length=451),
        ),
    ]
