# Generated by Django 5.2.1 on 2025-05-24 14:35

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_about_alter_doctor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_times',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('09:00 AM', '09:00 AM'), ('09:30 AM', '09:30 AM'), ('10:00 AM', '10:00 AM'), ('10:30 AM', '10:30 AM'), ('11:00 AM', '11:00 AM'), ('11:30 AM', '11:30 AM'), ('12:00 PM', '12:00 PM'), ('12:30 PM', '12:30 PM'), ('01:00 PM', '01:00 PM'), ('01:30 PM', '01:30 PM'), ('02:00 PM', '02:00 PM'), ('02:30 PM', '02:30 PM'), ('03:00 PM', '03:00 PM'), ('03:30 PM', '03:30 PM'), ('04:00 PM', '04:00 PM'), ('04:30 PM', '04:30 PM'), ('05:00 PM', '05:00 PM'), ('05:30 PM', '05:30 PM')], help_text='Select one or more consultation time slots', max_length=161),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('allergy_immunology', 'Allergy & Immunology'), ('anesthesiology', 'Anesthesiology'), ('audiology', 'Audiology'), ('cardiology', 'Cardiology'), ('critical_care', 'Critical Care Medicine'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('ent', 'ENT (Ear, Nose & Throat)'), ('family_medicine', 'Family Medicine'), ('gastroenterology', 'Gastroenterology'), ('general_medicine', 'General Medicine'), ('geriatrics', 'Geriatrics'), ('gynecology', 'Gynecology'), ('hematology', 'Hematology'), ('infectious_diseases', 'Infectious Diseases'), ('internal_medicine', 'Internal Medicine'), ('nephrology', 'Nephrology'), ('neurology', 'Neurology'), ('nuclear_medicine', 'Nuclear Medicine'), ('obstetrics', 'Obstetrics'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('pain_management', 'Pain Management'), ('pathology', 'Pathology'), ('pediatrics', 'Pediatrics'), ('plastic_surgery', 'Plastic Surgery'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology'), ('rheumatology', 'Rheumatology'), ('sports_medicine', 'Sports Medicine'), ('surgery', 'Surgery'), ('urology', 'Urology'), ('vascular_surgery', 'Vascular Surgery')], max_length=451),
        ),
    ]
