# Generated by Django 5.2.1 on 2025-06-07 10:12

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.TextField(blank=True, help_text='Use line breaks for paragraphs and * for bullet points.', null=True),
        ),
    ]
