# Generated by Django 5.2.1 on 2025-05-31 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor_consultation_times_doctorblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorblog',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='doctor.doctor'),
        ),
        migrations.CreateModel(
            name='DoctorVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Describe the video content for patients.')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='doctor_videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='doctor.doctor')),
            ],
        ),
    ]
