# Generated by Django 5.2.1 on 2025-06-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_family_member_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='proof_docs/'),
        ),
    ]
