# Generated by Django 5.2.1 on 2025-05-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='hospital_photos/')),
                ('email', models.EmailField(max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('contact_number2', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=128)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('location_map_url', models.URLField()),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
