# Generated by Django 5.2.1 on 2025-05-31 20:58

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='hospital_photos/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_number2', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=128)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('location_map_url', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('open_24_hours', models.BooleanField(default=False, help_text='Check if the hospital is open 24 hours')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hospital_gallery/')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, help_text='General description about the hospital.', null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ICU', 'ICU'), ('Ambulance', 'Ambulance'), ('Pharmacy', 'Pharmacy'), ('Blood Bank', 'Blood Bank'), ('Operation Theatre', 'Operation Theatre'), ('Lab', 'Lab'), ('Emergency', 'Emergency'), ('Canteen', 'Canteen'), ('Parking', 'Parking')], max_length=81)),
                ('hospital_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private'), ('Charitable', 'Charitable'), ('Specialized', 'Specialized'), ('Multi-Specialty', 'Multi-Specialty'), ('Teaching', 'Teaching')], max_length=62)),
                ('insurance_accepted', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Star Health', 'Star Health'), ('ICICI Lombard', 'ICICI Lombard'), ('Bajaj Allianz', 'Bajaj Allianz'), ('Reliance General', 'Reliance General'), ('Niva Bupa', 'Niva Bupa'), ('Care Health', 'Care Health'), ('Aditya Birla', 'Aditya Birla'), ('HDFC Ergo', 'HDFC Ergo')], max_length=101)),
                ('specialization', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allergy_immunology', 'Allergy & Immunology'), ('anesthesiology', 'Anesthesiology'), ('audiology', 'Audiology'), ('cardiology', 'Cardiology'), ('critical_care', 'Critical Care Medicine'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('ent', 'ENT (Ear, Nose & Throat)'), ('family_medicine', 'Family Medicine'), ('gastroenterology', 'Gastroenterology'), ('general_medicine', 'General Medicine'), ('geriatrics', 'Geriatrics'), ('gynecology', 'Gynecology'), ('hematology', 'Hematology'), ('infectious_diseases', 'Infectious Diseases'), ('internal_medicine', 'Internal Medicine'), ('nephrology', 'Nephrology'), ('neurology', 'Neurology'), ('nuclear_medicine', 'Nuclear Medicine'), ('obstetrics', 'Obstetrics'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('pain_management', 'Pain Management'), ('pathology', 'Pathology'), ('pediatrics', 'Pediatrics'), ('plastic_surgery', 'Plastic Surgery'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology'), ('rheumatology', 'Rheumatology'), ('sports_medicine', 'Sports Medicine'), ('surgery', 'Surgery'), ('urology', 'Urology'), ('vascular_surgery', 'Vascular Surgery')], max_length=451)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hospital.hospital')),
            ],
        ),
    ]
