# Generated by Django 5.2.1 on 2025-06-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='location_map_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldetails',
            name='about',
            field=models.TextField(blank=True, help_text='General description about the hospital.Use line breaks for paragraphs and * for bullet points.', null=True),
        ),
    ]
