# Generated by Django 5.2.1 on 2025-05-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='open_24_hours',
            field=models.BooleanField(default=False, help_text='Check if the hospital is open 24 hours'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
