# Generated by Django 5.2.1 on 2025-05-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_open_24_hours_alter_hospital_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='location_map_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
