# Generated by Django 5.2.1 on 2025-05-21 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_hospital_location_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hospital_gallery/')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='hospital.hospital')),
            ],
        ),
    ]
