# Generated by Django 5.2.1 on 2025-05-28 18:24

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospitalalbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(help_text='General description about the hospital.')),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('specializations', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Oncology', 'Oncology'), ('General Surgery', 'General Surgery'), ('Gynecology', 'Gynecology'), ('Dermatology', 'Dermatology'), ('ENT', 'ENT')], max_length=95)),
                ('services', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ICU', 'ICU'), ('Emergency', '24/7 Emergency'), ('Pharmacy', 'Pharmacy'), ('Diagnostics', 'Diagnostics'), ('Ambulance', 'Ambulance'), ('Blood Bank', 'Blood Bank'), ('Physiotherapy', 'Physiotherapy')], max_length=69)),
                ('facilities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Parking', 'Parking'), ('Canteen', 'Canteen'), ('WiFi', 'WiFi'), ('Waiting Area', 'Waiting Area'), ('ATM', 'ATM'), ('Wheelchair Access', 'Wheelchair Access')], max_length=55)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hospital.hospital')),
            ],
        ),
    ]
