# Generated by Django 5.2.1 on 2025-05-30 18:19

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospitalalbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ICU', 'ICU'), ('Ambulance', 'Ambulance'), ('Pharmacy', 'Pharmacy'), ('Blood Bank', 'Blood Bank'), ('Operation Theatre', 'Operation Theatre'), ('Lab', 'Lab'), ('Emergency', 'Emergency'), ('Canteen', 'Canteen'), ('Parking', 'Parking')], max_length=81)),
                ('hospital_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private'), ('Charitable', 'Charitable'), ('Specialized', 'Specialized'), ('Multi-Specialty', 'Multi-Specialty'), ('Teaching', 'Teaching')], max_length=62)),
                ('insurance_accepted', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Star Health', 'Star Health'), ('ICICI Lombard', 'ICICI Lombard'), ('Bajaj Allianz', 'Bajaj Allianz'), ('Reliance General', 'Reliance General'), ('Niva Bupa', 'Niva Bupa'), ('Care Health', 'Care Health'), ('Aditya Birla', 'Aditya Birla'), ('HDFC Ergo', 'HDFC Ergo')], max_length=101)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hospital.hospital')),
            ],
        ),
    ]
