# Generated by Django 5.2.1 on 2025-05-30 18:24

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_hospitaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldetails',
            name='specialization',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allergy_immunology', 'Allergy & Immunology'), ('anesthesiology', 'Anesthesiology'), ('audiology', 'Audiology'), ('cardiology', 'Cardiology'), ('critical_care', 'Critical Care Medicine'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('ent', 'ENT (Ear, Nose & Throat)'), ('family_medicine', 'Family Medicine'), ('gastroenterology', 'Gastroenterology'), ('general_medicine', 'General Medicine'), ('geriatrics', 'Geriatrics'), ('gynecology', 'Gynecology'), ('hematology', 'Hematology'), ('infectious_diseases', 'Infectious Diseases'), ('internal_medicine', 'Internal Medicine'), ('nephrology', 'Nephrology'), ('neurology', 'Neurology'), ('nuclear_medicine', 'Nuclear Medicine'), ('obstetrics', 'Obstetrics'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('pain_management', 'Pain Management'), ('pathology', 'Pathology'), ('pediatrics', 'Pediatrics'), ('plastic_surgery', 'Plastic Surgery'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology'), ('rheumatology', 'Rheumatology'), ('sports_medicine', 'Sports Medicine'), ('surgery', 'Surgery'), ('urology', 'Urology'), ('vascular_surgery', 'Vascular Surgery')], max_length=451),
        ),
    ]
